global:
  scrape_interval: 15s

rule_files:
  - "alerting.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'haproxy'
    metrics_path: /metrics
    static_configs:
      - targets: ['haproxy:8404']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
