apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-08-10T12:46:25Z"
  generation: 1
  labels:
    app: flasks-deployment
  name: flasks-deployment
  namespace: default
  resourceVersion: "57880"
  uid: 6de29e06-f6fa-4a59-84bb-60bc0a903524
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flasks-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flasks-deployment
    spec:
      containers:
      - image: mohamedhusseinomar/flask-app:v2
        imagePullPolicy: IfNotPresent
        name: flask-depi-r3-7szct
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2025-08-10T12:46:25Z"
    lastUpdateTime: "2025-08-10T12:46:29Z"
    message: ReplicaSet "flasks-deployment-bb9866db4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-08-23T09:02:49Z"
    lastUpdateTime: "2025-08-23T09:02:49Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
