apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "3"
    deployment.kubernetes.io/max-replicas: "4"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2025-08-09T18:45:10Z"
  generation: 1
  labels:
    app: nginx-deployment
    pod-template-hash: 6cfb98644c
  name: nginx-deployment-6cfb98644c
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: nginx-deployment
    uid: 42f0e861-f988-4e7f-9872-3acd624340c2
  resourceVersion: "5632"
  uid: cbc4aa58-a370-445c-8d13-52ed02f52845
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
      pod-template-hash: 6cfb98644c
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
        pod-template-hash: 6cfb98644c
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  fullyLabeledReplicas: 3
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
