- name: Configure Apache Web Server
  hosts: ubuntu_server
  become: true
  vars:
    package_name: apache2
  tasks:
    - name: insall apache web server
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt: 
        name: apache2

    - name: insall apache web server
      when: ansible_distribution == "RedHat"
      ansible.builtin.dnf: 
        name: httpd


    - name: Ensuring that apache is running 
      service:
        name: apache2
        state: started

    - name: Ensure that apache runs on port 8080
      notify: Ensuring that apache is restarted
      replace:
        regexp: "^Listen 80$"
        path: /etc/apache2/ports.conf
        replace: "Listen 8080"

  handlers:
    - name: Ensuring that apache is restarted 
      service:
        name: apache2
        state: restarted

    ## to do configure the apache to listen in port 8080
    ## and restart the apache
    ## use repalce module to replace the port
    #

    

