apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mariadb-svc
  name: mariadb-svc
spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb-svc
  type: ClusterIP
status:
  loadBalancer: {}
