apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mariadb
  name: mariadb
spec:
  containers:
  - env:
    - name: MYSQL_ROOT_PASSWORD
      value: secret
    image: mariadb:latest
    name: mariadb
    ports:
    - containerPort: 3306
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
