apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-database
  name: my-database
  namespace: databases
spec:
  containers:
  - image: mariadb
    name: my-database
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
