apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: database-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:11
          ports:
            - containerPort: 3306
          env:
            - name: MARIADB_ROOT_PASSWORD   
              value: "root"        
          readinessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -proot --host=127.0.0.1"]
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["sh", "-c", "mariadb-admin ping -proot --host=127.0.0.1"]
            initialDelaySeconds: 20
            periodSeconds: 10
